/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        eqx: {
          brand: 'rgb(var(--color-brand) / <alpha-value>)',
          'brand-strong': 'rgb(var(--color-brand-strong) / <alpha-value>)',
          'brand-text': 'rgb(var(--color-brand-text) / <alpha-value>)',
          action: 'rgb(var(--color-action) / <alpha-value>)',
          'action-hover': 'rgb(var(--color-action-hover) / <alpha-value>)',
          accent: 'rgb(var(--color-accent) / <alpha-value>)',
          'accent-text': 'rgb(var(--color-accent-text) / <alpha-value>)',
          bg: 'rgb(var(--color-bg) / <alpha-value>)',
          surface: 'rgb(var(--color-surface) / <alpha-value>)',
          'surface-subtle': 'rgb(var(--color-surface-subtle) / <alpha-value>)',
          'surface-strong': 'rgb(var(--color-surface-strong) / <alpha-value>)',
          text: 'rgb(var(--color-text) / <alpha-value>)',
          'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
          'text-inverse': 'rgb(var(--color-text-inverse) / <alpha-value>)',
          border: 'rgb(var(--color-border) / <alpha-value>)',
          'border-strong': 'rgb(var(--color-border-strong) / <alpha-value>)',
          focus: 'rgb(var(--color-focus) / <alpha-value>)',
          success: 'rgb(var(--color-success) / <alpha-value>)',
          'success-bg': 'rgb(var(--color-success-bg) / <alpha-value>)',
          warning: 'rgb(var(--color-warning) / <alpha-value>)',
          'warning-bg': 'rgb(var(--color-warning-bg) / <alpha-value>)',
          danger: 'rgb(var(--color-danger) / <alpha-value>)',
          'danger-bg': 'rgb(var(--color-danger-bg) / <alpha-value>)',
          info: 'rgb(var(--color-info) / <alpha-value>)',
          'info-bg': 'rgb(var(--color-info-bg) / <alpha-value>)',
          plum: 'rgb(var(--eqx-plum-600) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Open Sans', 'Arial', 'Helvetica', 'sans-serif'],
        mono: ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'monospace'],
      },
      fontSize: {
        xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-normal)' }],
        sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
        base: ['var(--font-size-base)', { lineHeight: 'var(--line-height-normal)' }],
        lg: ['var(--font-size-lg)', { lineHeight: 'var(--line-height-snug)' }],
        xl: ['var(--font-size-xl)', { lineHeight: 'var(--line-height-snug)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-snug)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        target: 'var(--size-target)',
        sidebar: 'var(--size-sidebar)',
      },
      maxWidth: {
        content: 'var(--size-content)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        1: 'var(--shadow-1)',
        2: 'var(--shadow-2)',
        3: 'var(--shadow-3)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        decelerate: 'var(--ease-decelerate)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '250ms',
        slow: '400ms',
      },
      zIndex: {
        dropdown: '50',
        sticky: '100',
        overlay: '200',
        modal: '300',
        toast: '400',
        tooltip: '500',
      },
      keyframes: {
        shimmer: { to: { backgroundPosition: '-200% 0' } },
      },
      animation: {
        shimmer: 'shimmer 1.5s infinite linear',
      },
    },
  },
  plugins: [],
};
